org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neoforge_version=26.1.2.95
neoforge_version_range=[26.1.2,)
java_version=25

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=2080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=2080

jei_version=29.29.0.77
rei_version=26.1.819
geckolib_version=5.5.2
ba_version=0.6.0.76
animatehitboxes_version=0.1.0

animatehitboxes_jar=libs/animatehitboxes-neoforge-26.1.2-0.1.0.jar

mod_id=voidmod
mod_version=0.1.0
mod_group=com.zavidvi.voidmod
archives_name=VoidMode

